//*** Note: apostrophes have been removed from player names; periods have not been removed

const rosters = {
    Team1: {
        QB1: {first: "Patrick", last: "Mahomes", ID: "13349"},
        QB2: {first: "Marcus", last: "Mariota", ID: "8640"},
        RB1: {first: "Phillip", last: "Lindsay", ID: "14830"},
        RB2: {first: "Derrick", last: "Henry", ID: "10043"},
        RB3: {first: "Sony", last: "Michel", ID: "14522"},
        RB4: {first: "Leonard", last: "Fournette", ID: "12606"},
        WR1: {first: "Tyreek", last: "Hill", ID: "9910"},
        WR2: {first: "Brandin", last: "Cooks", ID: "7656"},
        WR3: {first: "Chris", last: "Godwin", ID: "13493"},
        WR4: {first: "A.J.", last: "Green", ID: "6477"},
        WR5: {first: "Jordy", last: "Nelson", ID: "6932"},
        WR6: {first: "Eric", last: "Ebron", ID: "6845"},
        KIC: {first: "Kaimi", last: "Fairbairn", ID: "9686"},
        DEF: {city: "Baltimore", team: "Ravens", ID: "56"}
    },
    Team2: {
        QB1: {first: "Matt", last: "Ryan", ID: "6025"},
        QB2: {first: "Carson", last: "Wentz", ID: "9712"},
        RB1: {first: "James", last: "White", ID: "7558"},
        RB2: {first: "Chris", last: "Carson", ID: "13114"},
        RB3: {first: "Peyton", last: "Barber", ID: "10068"},
        RB4: {first: "Nyheim", last: "Hines", ID: "14696"},
        WR1: {first: "Antonio", last: "Brown", ID: "8109"},
        WR2: {first: "Keenan", last: "Allen", ID: "8199"},
        WR3: {first: "Alshon", last: "Jeffery", ID: "6386"},
        WR4: {first: "DJ", last: "Moore", ID: "14515"},
        WR5: {first: "Doug", last: "Baldwin", ID: "8292"},
        WR6: {first: "Jared", last: "Cook", ID: "8487"},
        KIC: {first: "Justin", last: "Tucker", ID: "6198"},
        DEF: {city: "Minnesota", team: "Vikings", ID: "63"}
    },
    Team3: {
        QB1: {first: "Ben", last: "Roethlisberger", ID: "8100"},
        QB2: {first: "Jameis", last: "Winston", ID: "8550"},
        RB1: {first: "David", last: "Johnson", ID: "5940"},
        RB2: {first: "Nick", last: "Chubb", ID: "14672"},
        RB3: {first: "Austin", last: "Ekeler", ID: "13378"},
        RB4: {first: "Alex", last: "Collins", ID: "10014"},
        WR1: {first: "Davante", last: "Adams", ID: "6924"},
        WR2: {first: "T.Y.", last: "Hilton", ID: "7105"},
        WR3: {first: "Corey", last: "Davis", ID: "12670"},
        WR4: {first: "John", last: "Brown", ID: "5945"},
        WR5: {first: "Antonio", last: "Callaway", ID: "14673"},
        WR6: {first: "Trey", last: "Burton", ID: "8030"},
        KIC: {first: "Jason", last: "Myers", ID: "7266"},
        DEF: {city: "Kansas City", team: "Chiefs", ID: "73"}
    },
    Team4: {
        QB1: {first: "Deshaun", last: "Watson", ID: "13027"},
        QB2: {first: "Josh", last: "Allen", ID: "8575"},
        RB1: {first: "Joe", last: "Mixon", ID: "12843"},
        RB2: {first: "Adrian", last: "Peterson", ID: "7466"},
        RB3: {first: "Mark", last: "Ingram II", ID: "7647"},
        RB4: {first: "LeSean", last: "McCoy", ID: "6209"},
        WR1: {first: "DeAndre", last: "Hopkins", ID: "7013"},
        WR2: {first: "Odell", last: "Beckham Jr.", ID: "7746"},
        WR3: {first: "Larry", last: "Fitzgerald", ID: "5946"},
        WR4: {first: "Nelson", last: "Agholor", ID: "8019"},
        WR5: {first: "Anthony", last: "Miller", ID: "14665"},
        WR6: {first: "Austin", last: "Hooper", ID: "9741"},
        KIC: {first: "Wil", last: "Lutz", ID: "10054"},
        DEF: {city: "Denver", team: "Broncos", ID: "72"}
    },
    Team5: {
        QB1: {first: "Andrew", last: "Luck", ID: "7093"},
        QB2: {first: "Matthew", last: "Stafford", ID: "6825"},
        RB1: {first: "Kareem", last: "Hunt", ID: "13330"},
        RB2: {first: "Tarik", last: "Cohen", ID: "12816"},
        RB3: {first: "Isaiah", last: "Crowell", ID: "6558"},
        RB4: {first: "Frank", last: "Gore", ID: "7096"},
        WR1: {first: "Julio", last: "Jones", ID: "6038"},
        WR2: {first: "Tyler", last: "Boyd", ID: "9797"},
        WR3: {first: "Sterling", last: "Shepard", ID: "9960"},
        WR4: {first: "Allen", last: "Robinson", ID: "7198"},
        WR5: {first: "Cole", last: "Beasley", ID: "6657"},
        WR6: {first: "David", last: "Njoku", ID: "12875"},
        KIC: {first: "Harrison", last: "Butker", ID: "12796"},
        DEF: {city: "Seattle", team: "Seahawks", ID: "79"}
    },
    Team6: {
        QB1: {first: "Aaron", last: "Rodgers", ID: "6914"},
        QB2: {first: "Case", last: "Keenum", ID: "8464"},
        RB1: {first: "James", last: "Conner", ID: "13188"},
        RB2: {first: "Tevin", last: "Coleman", ID: "6027"},
        RB3: {first: "T.J.", last: "Yeldon", ID: "7189"},
        RB4: {first: "Wendell", last: "Smallwood", ID: "9710"},
        WR1: {first: "Mike", last: "Evans", ID: "8562"},
        WR2: {first: "Calvin", last: "Ridley", ID: "14517"},
        WR3: {first: "Mohamed", last: "Sanu", ID: "6483"},
        WR4: {first: "Curtis", last: "Samuel", ID: "12811"},
        WR5: {first: "Taylor", last: "Gabriel", ID: "6567"},
        WR6: {first: "Travis", last: "Kelce", ID: "7299"},
        KIC: {first: "Mason", last: "Crosby", ID: "6997"},
        DEF: {city: "Washington", team: "Redskins", ID: "55"}
    },
    Team7: {
        QB1: {first: "Jared", last: "Goff", ID: "9919"},
        QB2: {first: "Derek", last: "Carr", ID: "7916"},
        RB1: {first: "Melvin", last: "Gordon", ID: "8195"},
        RB2: {first: "Marlon", last: "Mack", ID: "13047"},
        RB3: {first: "Dalvin", last: "Cook", ID: "13132"},
        RB4: {first: "Jalen", last: "Richard", ID: "9979"},
        WR1: {first: "Adam", last: "Thielen", ID: "7478"},
        WR2: {first: "Amari", last: "Cooper", ID: "7929"},
        WR3: {first: "Adam", last: "Humphries", ID: "8565"},
        WR4: {first: "Demaryius", last: "Thomas", ID: "6757"},
        WR5: {first: "Donte", last: "Moncrief", ID: "7108"},
        WR6: {first: "George", last: "Kittle", ID: "13457"},
        KIC: {first: "Aldrick", last: "Rosas", ID: "13101"},
        DEF: {city: "Indianapolis", team: "Colts", ID: "65"}
    },
    Team8: {
        QB1: {first: "Drew", last: "Brees", ID: "7641"},
        QB2: {first: "Eli", last: "Manning", ID: "7734"},
        RB1: {first: "Ezekiel", last: "Elliott", ID: "9839"},
        RB2: {first: "Jordan", last: "Howard", ID: "9791"},
        RB3: {first: "Latavius", last: "Murray", ID: "7924"},
        RB4: {first: "Carlos", last: "Hyde", ID: "8381"},
        WR1: {first: "Michael", last: "Thomas", ID: "7450"},
        WR2: {first: "Mike", last: "Williams", ID: "13398"},
        WR3: {first: "DeSean", last: "Jackson", ID: "8748"},
        WR4: {first: "Josh", last: "Gordon", ID: "6568"},
        WR5: {first: "Marvin", last: "Jones Jr.", ID: "6479"},
        WR6: {first: "Zach", last: "Ertz", ID: "8032"},
        KIC: {first: "Robbie", last: "Gould", ID: "6460"},
        DEF: {city: "Tennessee", team: "Titans", ID: "67"}
    },
    Team9: {
        QB1: {first: "Russell", last: "Wilson", ID: "8283"},
        QB2: {first: "Baker", last: "Mayfield", ID: "14492"},
        RB1: {first: "Alvin", last: "Kamara", ID: "13255"},
        RB2: {first: "Kenyan", last: "Drake", ID: "9694"},
        RB3: {first: "Kerryon", last: "Johnson", ID: "14686"},
        RB4: {first: "Gus", last: "Edwards", ID: "14849"},
        WR1: {first: "JuJu", last: "Smith-Schuster", ID: "13203"},
        WR2: {first: "Kenny", last: "Golladay", ID: "12943"},
        WR3: {first: "Zay", last: "Jones", ID: "12769"},
        WR4: {first: "Kenny", last: "Stills", ID: "7386"},
        WR5: {first: "Christian", last: "Kirk", ID: "14654"},
        WR6: {first: "Kyle", last: "Rudolph", ID: "7485"},
        KIC: {first: "Stephen", last: "Gostkowski", ID: "7638"},
        DEF: {city: "Pittsburgh", team: "Steelers", ID: "59"}
    },
    Team10: {
        QB1: {first: "Dak", last: "Prescott", ID: "9845"},
        QB2: {first: "Mitchell", last: "Trubisky", ID: "12831"},
        RB1: {first: "Christian", last: "McCaffrey", ID: "12807"},
        RB2: {first: "Lamar", last: "Miller", ID: "7372"},
        RB3: {first: "Mike", last: "Davis", ID: "8377"},
        RB4: {first: "Jamaal", last: "Williams", ID: "12999"},
        WR1: {first: "Robert", last: "Woods", ID: "6225"},
        WR2: {first: "Jarvis", last: "Landry", ID: "7380"},
        WR3: {first: "Golden", last: "Tate", ID: "6844"},
        WR4: {first: "Tyrell", last: "Williams", ID: "8208"},
        WR5: {first: "Rashard", last: "Higgins", ID: "9823"},
        WR6: {first: "O.J.", last: "Howard", ID: "13491"},
        KIC: {first: "Brett", last: "Maher", ID: "14978"},
        DEF: {city: "Houston", team: "Texans", ID: "64"}
    },
    Team11: {
        QB1: {first: "Philip", last: "Rivers", ID: "8190"},
        QB2: {first: "Tom", last: "Brady", ID: "7549"},
        RB1: {first: "Saquon", last: "Barkley", ID: "14493"},
        RB2: {first: "Aaron", last: "Jones", ID: "12978"},
        RB3: {first: "Doug", last: "Martin", ID: "8554"},
        RB4: {first: "Royce", last: "Freeman", ID: "14680"},
        WR1: {first: "Tyler", last: "Lockett", ID: "8296"},
        WR2: {first: "Julian", last: "Edelman", ID: "7564"},
        WR3: {first: "Dede", last: "Westbrook", ID: "13362"},
        WR4: {first: "Cooper", last: "Kupp", ID: "13412"},
        WR5: {first: "Devin", last: "Funchess", ID: "6309"},
        WR6: {first: "Rob", last: "Gronkowski", ID: "7575"},
        KIC: {first: "Matt", last: "Prater", ID: "6908"},
        DEF: {city: "Los Angeles", team: "Rams", ID: "77"}
    },
    Team12: {
        QB1: {first: "Kirk", last: "Cousins", ID: "8731"},
        QB2: {first: "Cam", last: "Newton", ID: "6294"},
        RB1: {first: "Todd", last: "Gurley II", ID: "8469"},
        RB2: {first: "Matt", last: "Breida", ID: "13466"},
        RB3: {first: "Dion", last: "Lewis", ID: "7557"},
        RB4: {first: "Duke", last: "Johnson Jr.", ID: "6560"},
        WR1: {first: "Stefon", last: "Diggs", ID: "7471"},
        WR2: {first: "Emmanuel", last: "Sanders", ID: "6756"},
        WR3: {first: "Robby", last: "Anderson", ID: "9961"},
        WR4: {first: "Courtland", last: "Sutton", ID: "14682"},
        WR5: {first: "Michael", last: "Crabtree", ID: "7930"},
        WR6: {first: "Vance", last: "McDonald", ID: "8403"},
        KIC: {first: "Sebastian", last: "Janikowski", ID: "8003"},
        DEF: {city: "Chicago", team: "Bears", ID: "60"}
    }
};