const rosters = {
    Team1: {
        QB1:{first:"Patrick", last: "Mahomes"},
        QB2:{first:"Marcus", last: "Mariota"},
        RB1:{first:"Phillip", last: "Lindsay"},
        RB2:{first:"Derrick", last: "Henry"},
        RB3:{first:"Sony", last: "Michel"},
        RB4:{first:"Leonard", last: "Fournette"},
        WR1:{first:"Tyreek", last: "Hill"},
        WR2:{first:"Brandin", last: "Cooks"},
        WR3:{first:"Chris", last: "Godwin"},
        WR4:{first:"A.J.", last: "Green"},
        WR5:{first:"Jordy", last: "Nelson"},
        WR6:{first:"Eric", last: "Ebron"},
        KIC:{first:"Kaimi", last: "Fairbairn"},
        DEF:{first:"Baltimore", last: "Ravens"}
    },
    Team2: {
        QB1:{first:"Matt", last: "Ryan"},
        QB2:{first:"Carson", last: "Wentz"},
        RB1:{first:"James", last: "White"},
        RB2:{first:"Chris", last: "Carson"},
        RB3:{first:"Peyton", last: "Barber"},
        RB4:{first:"Nyheim", last: "Hines"},
        WR1:{first:"Antonio", last: "Brown"},
        WR2:{first:"Keenan", last: "Allen"},
        WR3:{first:"Alshon", last: "Jeffery"},
        WR4:{first:"D.J.", last: "Moore"},
        WR5:{first:"Doug", last: "Baldwin"},
        WR6:{first:"Jared", last: "Cook"},
        KIC:{first:"Justin", last: "Tucker"},
        DEF:{first:"Minnesota", last: "Vikings"}
    },
    Team3: {
        QB1:{first:"Ben", last: "Roethlisberger"},
        QB2:{first:"Jameis", last: "Winston"},
        RB1:{first:"David", last: "Johnson"},
        RB2:{first:"Nick", last: "Chubb"},
        RB3:{first:"Austin", last: "Ekeler"},
        RB4:{first:"Alex", last: "Collins"},
        WR1:{first:"Davante", last: "Adams"},
        WR2:{first:"T.Y.", last: "Hilton"},
        WR3:{first:"Corey", last: "Davis"},
        WR4:{first:"John", last: "Brown"},
        WR5:{first:"Antonio", last: "Callaway"},
        WR6:{first:"Trey", last: "Burton"},
        KIC:{first:"Jason", last: "Myers"},
        DEF:{first:"Kansas", last: "City", last: "Chiefs"}
    },
    Team4: {
        QB1:{first:"Deshaun", last: "Watson"},
        QB2:{first:"Josh", last: "Allen"},
        RB1:{first:"Joe", last: "Mixon"},
        RB2:{first:"Adrian", last: "Peterson"},
        RB3:{first:"Mark", last: "Ingram"},
        RB4:{first:"LeSean", last: "McCoy"},
        WR1:{first:"DeAndre", last: "Hopkins"},
        WR2:{first:"Odell", last: "Beckham", last: "Jr."},
        WR3:{first:"Larry", last: "Fitzgerald"},
        WR4:{first:"Nelson", last: "Agholor"},
        WR5:{first:"Anthony", last: "Miller"},
        WR6:{first:"Austin", last: "Hooper"},
        KIC:{first:"Wil", last: "Lutz"},
        DEF:{first:"Denver", last: "Broncos"}
    },
    Team5: {
        QB1:{first:"Andrew", last: "Luck"},
        QB2:{first:"Matthew", last: "Stafford"},
        RB1:{first:"Kareem", last: "Hunt"},
        RB2:{first:"Tarik", last: "Cohen"},
        RB3:{first:"Isaiah", last: "Crowell"},
        RB4:{first:"Frank", last: "Gore"},
        WR1:{first:"Julio", last: "Jones"},
        WR2:{first:"Tyler", last: "Boyd"},
        WR3:{first:"Sterling", last: "Shepard"},
        WR4:{first:"Allen", last: "Robinson"},
        WR5:{first:"Cole", last: "Beasley"},
        WR6:{first:"David", last: "Njoku"},
        KIC:{first:"Harrison", last: "Butker"},
        DEF:{first:"Seattle", last: "Seahawks"}
    },
    Team6: {
        QB1:{first:"Aaron", last: "Rodgers"},
        QB2:{first:"Case", last: "Keenum"},
        RB1:{first:"James", last: "Conner"},
        RB2:{first:"Tevin", last: "Coleman"},
        RB3:{first:"T.J.", last: "Yeldon"},
        RB4:{first:"Wendell", last: "Smallwood"},
        WR1:{first:"Mike", last: "Evans"},
        WR2:{first:"Calvin", last: "Ridley"},
        WR3:{first:"Mohamed", last: "Sanu"},
        WR4:{first:"Curtis", last: "Samuel"},
        WR5:{first:"Taylor", last: "Gabriel"},
        WR6:{first:"Travis", last: "Kelce"},
        KIC:{first:"Mason", last: "Crosby"},
        DEF:{first:"Washington", last: "Redskins"}
    },
    Team7: {
        QB1:{first:"Jared", last: "Goff"},
        QB2:{first:"Derek", last: "Carr"},
        RB1:{first:"Melvin", last: "Gordon"},
        RB2:{first:"Marlon", last: "Mack"},
        RB3:{first:"Dalvin", last: "Cook"},
        RB4:{first:"Jalen", last: "Richard"},
        WR1:{first:"Adam", last: "Thielen"},
        WR2:{first:"Amari", last: "Cooper"},
        WR3:{first:"Adam", last: "Humphries"},
        WR4:{first:"Demaryius", last: "Thomas"},
        WR5:{first:"Donte", last: "Moncrief"},
        WR6:{first:"George", last: "Kittle"},
        KIC:{first:"Aldrick", last: "Rosas"},
        DEF:{first:"Indianapolis", last: "Colts"}
    },
    Team8: {
        QB1:{first:"Drew", last: "Brees"},
        QB2:{first:"Eli", last: "Manning"},
        RB1:{first:"Ezekiel", last: "Elliott"},
        RB2:{first:"Jordan", last: "Howard"},
        RB3:{first:"Latavius", last: "Murray"},
        RB4:{first:"Carlos", last: "Hyde"},
        WR1:{first:"Michael", last: "Thomas"},
        WR2:{first:"Mike", last: "Williams"},
        WR3:{first:"DeSean", last: "Jackson"},
        WR4:{first:"Josh", last: "Gordon"},
        WR5:{first:"Marvin", last: "Jones"},
        WR6:{first:"Zach", last: "Ertz"},
        KIC:{first:"Robbie", last: "Gould"},
        DEF:{first:"Tennessee", last: "Titans"}
    },
    Team9: {
        QB1:{first:"Russell", last: "Wilson"},
        QB2:{first:"Baker", last: "Mayfield"},
        RB1:{first:"Alvin", last: "Kamara"},
        RB2:{first:"Kenyan", last: "Drake"},
        RB3:{first:"Kerryon", last: "Johnson"},
        RB4:{first:"Gus", last: "Edwards"},
        WR1:{first:"JuJu", last: "Smith-Schuster"},
        WR2:{first:"Kenny", last: "Golladay"},
        WR3:{first:"Zay", last: "Jones"},
        WR4:{first:"Kenny", last: "Stills"},
        WR5:{first:"Christian", last: "Kirk"},
        WR6:{first:"Kyle", last: "Rudolph"},
        KIC:{first:"Stephen", last: "Gostkowski"},
        DEF:{first:"Pittsburgh", last: "Steelers"}
    },
    Team10: {
        QB1:{first:"Dak", last: "Prescott"},
        QB2:{first:"Mitchell", last: "Trubisky"},
        RB1:{first:"Christian", last: "McCaffrey"},
        RB2:{first:"Lamar", last: "Miller"},
        RB3:{first:"Mike", last: "Davis"},
        RB4:{first:"Jamaal", last: "Williams"},
        WR1:{first:"Robert", last: "Woods"},
        WR2:{first:"Jarvis", last: "Landry"},
        WR3:{first:"Golden", last: "Tate"},
        WR4:{first:"Tyrell", last: "Williams"},
        WR5:{first:"Rashard", last: "Higgins"},
        WR6:{first:"O.J.", last: "Howard"},
        KIC:{first:"Brett", last: "Maher"},
        DEF:{first:"Houston", last: "Texans"}
    },
    Team11: {
        QB1:{first:"Philip", last: "Rivers"},
        QB2:{first:"Tom", last: "Brady"},
        RB1:{first:"Saquon", last: "Barkley"},
        RB2:{first:"Aaron", last: "Jones"},
        RB3:{first:"Doug", last: "Martin"},
        RB4:{first:"Royce", last: "Freeman"},
        WR1:{first:"Tyler", last: "Lockett"},
        WR2:{first:"Julian", last: "Edelman"},
        WR3:{first:"Dede", last: "Westbrook"},
        WR4:{first:"Cooper", last: "Kupp"},
        WR5:{first:"Devin", last: "Funchess"},
        WR6:{first:"Rob", last: "Gronkowski"},
        KIC:{first:"Matt", last: "Prater"},
        DEF:{first:"Los Angeles", last: "Rams"}
    },
    Team12: {
        QB1:{first:"Kirk", last: "Cousins"},
        QB2:{first:"Cam", last: "Newton"},
        RB1:{first:"Todd", last: "Gurley"},
        RB2:{first:"Matt", last: "Breida"},
        RB3:{first:"Dion", last: "Lewis"},
        RB4:{first:"Duke", last: "Johnson"},
        WR1:{first:"Stefon", last: "Diggs"},
        WR2:{first:"Emmanuel", last: "Sanders"},
        WR3:{first:"Robby", last: "Anderson"},
        WR4:{first:"Courtland", last: "Sutton"},
        WR5:{first:"Michael", last: "Crabtree"},
        WR6:{first:"Vance", last: "McDonald"},
        KIC:{first:"Sebastian", last: "Janikowski"},
        DEF:{first:"Chicago", last: "Bears"}
    }
};