const rosters = {
    Team1: {
        QB1: "Patrick Mahomes",
        QB2: "Marcus Mariota",
        RB1: "Phillip Lindsay",
        RB2: "Derrick Henry",
        RB3: "Sony Michel",
        RB4: "Leonard Fournette",
        WR1: "Tyreek Hill",
        WR2: "Brandin Cooks",
        WR3: "Chris Godwin",
        WR4: "A.J. Green",
        WR5: "Jordy Nelson",
        WR6: "Eric Ebron",
        KIC: "Kaimi Fairbairn",
        DEF: "Baltimore Ravens"
    },
    Team2: {
        QB1: "Matt Ryan",
        QB2: "Carson Wentz",
        RB1: "James White",
        RB2: "Chris Carson",
        RB3: "Peyton Barber",
        RB4: "Nyheim Hines",
        WR1: "Antonio Brown",
        WR2: "Keenan Allen",
        WR3: "Alshon Jeffery",
        WR4: "D.J. Moore",
        WR5: "Doug Baldwin",
        WR6: "Jared Cook",
        KIC: "Justin Tucker",
        DEF: "Minnesota Vikings"
    },
    Team3: {
        QB1: "Ben Roethlisberger",
        QB2: "Jameis Winston",
        RB1: "David Johnson",
        RB2: "Nick Chubb",
        RB3: "Austin Ekeler",
        RB4: "Alex Collins",
        WR1: "Davante Adams",
        WR2: "T.Y. Hilton",
        WR3: "Corey Davis",
        WR4: "John Brown",
        WR5: "Antonio Callaway",
        WR6: "Trey Burton",
        KIC: "Jason Myers",
        DEF: "Kansas City Chiefs"
    },
    Team4: {
        QB1: "Deshaun Watson",
        QB2: "Josh Allen",
        RB1: "Joe Mixon",
        RB2: "Adrian Peterson",
        RB3: "Mark Ingram",
        RB4: "LeSean McCoy",
        WR1: "DeAndre Hopkins",
        WR2: "Odell Beckham Jr.",
        WR3: "Larry Fitzgerald",
        WR4: "Nelson Agholor",
        WR5: "Anthony Miller",
        WR6: "Austin Hooper",
        KIC: "Wil Lutz",
        DEF: "Denver Broncos"
    },
    Team5: {
        QB1: "Andrew Luck",
        QB2: "Matthew Stafford",
        RB1: "Kareem Hunt",
        RB2: "Tarik Cohen",
        RB3: "Isaiah Crowell",
        RB4: "Frank Gore",
        WR1: "Julio Jones",
        WR2: "Tyler Boyd",
        WR3: "Sterling Shepard",
        WR4: "Allen Robinson",
        WR5: "Cole Beasley",
        WR6: "David Njoku",
        KIC: "Harrison Butker",
        DEF: "Seattle Seahawks"
    },
    Team6: {
        QB1: "Aaron Rodgers",
        QB2: "Case Keenum",
        RB1: "James Conner",
        RB2: "Tevin Coleman",
        RB3: "T.J. Yeldon",
        RB4: "Wendell Smallwood",
        WR1: "Mike Evans",
        WR2: "Calvin Ridley",
        WR3: "Mohamed Sanu",
        WR4: "Curtis Samuel",
        WR5: "Taylor Gabriel",
        WR6: "Travis Kelce",
        KIC: "Mason Crosby",
        DEF: "Washington Redskins"
    },
    Team7: {
        QB1: "Jared Goff",
        QB2: "Derek Carr",
        RB1: "Melvin Gordon",
        RB2: "Marlon Mack",
        RB3: "Dalvin Cook",
        RB4: "Jalen Richard",
        WR1: "Adam Thielen",
        WR2: "Amari Cooper",
        WR3: "Adam Humphries",
        WR4: "Demaryius Thomas",
        WR5: "Donte Moncrief",
        WR6: "George Kittle",
        KIC: "Aldrick Rosas",
        DEF: "Indianapolis Colts"
    },
    Team8: {
        QB1: "Drew Brees",
        QB2: "Eli Manning",
        RB1: "Ezekiel Elliott",
        RB2: "Jordan Howard",
        RB3: "Latavius Murray",
        RB4: "Carlos Hyde",
        WR1: "Michael Thomas",
        WR2: "Mike Williams",
        WR3: "DeSean Jackson",
        WR4: "Josh Gordon",
        WR5: "Marvin Jones",
        WR6: "Zach Ertz",
        KIC: "Robbie Gould",
        DEF: "Tennessee Titans"
    },
    Team9: {
        QB1: "Russell Wilson",
        QB2: "Baker Mayfield",
        RB1: "Alvin Kamara",
        RB2: "Kenyan Drake",
        RB3: "Kerryon Johnson",
        RB4: "Gus Edwards",
        WR1: "JuJu Smith-Schuster",
        WR2: "Kenny Golladay",
        WR3: "Zay Jones",
        WR4: "Kenny Stills",
        WR5: "Christian Kirk",
        WR6: "Kyle Rudolph",
        KIC: "Stephen Gostkowski",
        DEF: "Pittsburgh Steelers"
    },
    Team10: {
        QB1: "Dak Prescott",
        QB2: "Mitchell Trubisky",
        RB1: "Christian McCaffrey",
        RB2: "Lamar Miller",
        RB3: "Mike Davis",
        RB4: "Jamaal Williams",
        WR1: "Robert Woods",
        WR2: "Jarvis Landry",
        WR3: "Golden Tate",
        WR4: "Tyrell Williams",
        WR5: "Rashard Higgins",
        WR6: "O.J. Howard",
        KIC: "Brett Maher",
        DEF: "Houston Texans"
    },
    Team11: {
        QB1: "Philip Rivers",
        QB2: "Tom Brady",
        RB1: "Saquon Barkley",
        RB2: "Aaron Jones",
        RB3: "Doug Martin",
        RB4: "Royce Freeman",
        WR1: "Tyler Lockett",
        WR2: "Julian Edelman",
        WR3: "Dede Westbrook",
        WR4: "Cooper Kupp",
        WR5: "Devin Funchess",
        WR6: "Rob Gronkowski",
        KIC: "Matt Prater",
        DEF: "Los Angeles Rams"
    },
    Team12: {
        QB1: "Kirk Cousins",
        QB2: "Cam Newton",
        RB1: "Todd Gurley",
        RB2: "Matt Breida",
        RB3: "Dion Lewis",
        RB4: "Duke Johnson",
        WR1: "Stefon Diggs",
        WR2: "Emmanuel Sanders",
        WR3: "Robby Anderson",
        WR4: "Courtland Sutton",
        WR5: "Michael Crabtree",
        WR6: "Vance McDonald",
        KIC: "Sebastian Janikowski",
        DEF: "Chicago Bears"
    }
};